---
- name: Download Fly
  become: true
  get_url:
    url: https://github.com/concourse/concourse/releases/download/{{ concourse_version }}/fly_linux_amd64
    dest: /usr/local/bin/fly
    mode: 0755
