---
- name: Install Snap
  become: true
  shell: |
    apt install snap

- name: Install VSCode
  become: true
  shell: |
    snap install vscode --classic

- name: Install extensions
  shell: |
    code --install-extension bungcip.better-toml
    code --install-extension DavidAnson.vscode-markdownlint
    code --install-extension dunstontc.dark-plus-syntax
    code --install-extension eriklynd.json-tools
    code --install-extension ms-python.python
    code --install-extension ms-vscode.Go
    code --install-extension PeterJausovec.vscode-docker
    code --install-extension robertohuertasm.vscode-icons
    code --install-extension wayou.vscode-todo-highlight

- name: Create Directory
  become: true
  file:
    path: "~/.config/Code/User/"
    state: directory

- name: Add configurations
  copy:
    src: "/tmp/Ubuntu1804_ansible_setup/setup/ansible/roles/vscode/files/settings.json"
    dest:  "~/.config/Code/User/settings.json"
