---
- name: Get git-duet
  become: true
  unarchive:
    src: https://github.com/git-duet/git-duet/releases/download/{{ duet_version }}/linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
- name: Copy Git authors
  copy:
    src: "../files/.git-authors"
    dest:  "~/.git-authors"
- name: insert our custom stuff to .bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "# GIT-DUET CUSTOM SAUCE"
    block: |
      export GIT_DUET_ROTATE_AUTHOR=1
      export GIT_DUET_GLOBAL=true
      git config --global alias.ci duet-commit
