---
- name: install docker step 1
  become: true
  shell: |
    apt install -y apt-transport-https ca-certificates curl software-properties-common
  args:
    executable: /bin/bash

- name: install docker step 2
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  args:
    executable: /bin/bash

- name: install docker step 3
  become: true
  shell: |
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    apt update
    apt install -y docker-ce
  args:
    executable: /bin/bash

- name: configure docker
  become: true
  shell: |
    usermod -aG docker tom
    systemctl enable docker
  args:
    executable: /bin/bash

- name: Copy scripts
  become: true
  copy:
    src: "../files/scripts/"
    dest:  "/usr/local/bin/"
    mode: 0777

- name: Ethan's Docker directory creation
  become: true
  file:
    path: "/etc/docker"
    state: directory
    mode: 0700

- name: Copy config
  become: true
  copy:
    src: "../files/daemon.json"
    dest:  "/etc/docker/daemon.json"

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
